name: Build and Push Container Image

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ["catch2", "lua", "pytest", "yarn"]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Configure Podman storage (vfs)
        run: |
          mkdir -p ~/.config/containers
          echo -e "[storage]\ndriver = \"vfs\"" > ~/.config/containers/storage.conf

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | podman login ghcr.io \
            --username marek629 \
            --password-stdin

      - name: Build image
        run: |
          podman build \
            --build-arg target=${{ matrix.target }} \
            -t ghcr.io/marek629/kiro-cli:${{ matrix.target }} .

      - name: Push image
        run: |
          podman push ghcr.io/marek629/kiro-cli:${{ matrix.target }}
